#define SERVER_PORT 8050
#define SHARED_SECRET_KEY "ELECS212-2010"
#define MAX_MESSAGE_LENGTH 256
#define MAX_USER_NAME_LENGTH 21
#define MAX_CHALLENGE_LENGTH 21
#define SOCKET_ADDRESS struct sockaddr_in
